import type { ManualRule } from '../../types/manual';

export const MANUAL_RULES: ManualRule[] = [
  {
    id: 1,
    title: "Drink.",
    category: "BASIC",
    instruction: "Take 1 {UNIT}.",
    failure: "You hesitate (more than 2 seconds) after the card appears.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["starter"],
    modeWeights: { basic: 6, field: 5, final: 4 },
  },
  {
    id: 2,
    title: "Drink Again.",
    category: "BASIC",
    instruction: "Take 2 consecutive {UNIT_PLURAL}.",
    failure: "You pause more than 2 seconds between them.",
    penalty: "Take a 3rd {UNIT}.",
    tags: ["pace"],
    modeWeights: { basic: 5, field: 5, final: 4 },
  },
  {
    id: 3,
    title: "Commitment",
    category: "BASIC",
    instruction: "Finish your current drink OR take 2 {UNIT_PLURAL}.",
    failure: "You leave any liquid after choosing to finish.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["finish"],
    modeWeights: { basic: 3, field: 4, final: 5 },
  },
  {
    id: 4,
    title: "No Pause Sip",
    category: "BASIC",
    instruction: "Take 1 {UNIT} without stopping mid-sip.",
    failure: "You stop mid-sip.",
    penalty: "Repeat the instruction (another 1 {UNIT}).",
    tags: ["clean"],
    modeWeights: { basic: 5, field: 4, final: 4 },
  },
  {
    id: 5,
    title: "Two-Handed Shame",
    category: "BASIC",
    instruction: "Take 1 {UNIT} using two hands on the cup/glass.",
    failure: "You use one hand.",
    penalty: "Take 1 additional {UNIT} normally.",
    tags: ["dumb"],
    modeWeights: { basic: 4, field: 4, final: 3 },
  },
  {
    id: 6,
    title: "Clean Sip",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} without making any sound.",
    failure: "Any audible gulp, slurp, or lip smack.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["quiet"],
    modeWeights: { basic: 5, field: 4, final: 3 },
  },
  {
    id: 7,
    title: "Non-Dominant Hand",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} using your non-dominant hand only.",
    failure: "Your dominant hand touches the drink.",
    penalty: "Take 1 extra {UNIT} normally.",
    tags: ["coordination"],
    modeWeights: { basic: 4, field: 4, final: 4 },
  },
  {
    id: 8,
    title: "One-Leg Technique",
    category: "TECHNIQUE",
    instruction: "Stand on one leg and take 1 {UNIT}.",
    failure: "Your lifted foot touches the ground during the sip.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["balance"],
    modeWeights: { basic: 3, field: 4, final: 4 },
  },
  {
    id: 9,
    title: "Three-Second Timing",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} in exactly 3 seconds (counted out loud by the group).",
    failure: "You finish before '3' or after '3'.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["timing"],
    modeWeights: { basic: 3, field: 4, final: 5 },
  },
  {
    id: 10,
    title: "No Look",
    category: "TECHNIQUE",
    instruction: "Close your eyes and take 1 {UNIT}.",
    failure: "Eyes open at any point during the sip.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["discipline"],
    modeWeights: { basic: 4, field: 4, final: 3 },
  },
  {
    id: 11,
    title: "No Thinking",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT} immediately.",
    failure: 'You ask any question or say any hesitation phrase (e.g., "wait", "hold on").',
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["fast"],
    modeWeights: { basic: 4, field: 5, final: 6 },
  },
  {
    id: 12,
    title: "Deadpan",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT} with a straight face.",
    failure: "You laugh, smile, or react verbally during/after the sip.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["composure"],
    modeWeights: { basic: 4, field: 4, final: 4 },
  },
  {
    id: 13,
    title: "No Comment",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT} and say nothing for 10 seconds after.",
    failure: "You speak or make a sound in the 10 seconds.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["silence"],
    modeWeights: { basic: 3, field: 4, final: 5 },
  },
  {
    id: 14,
    title: "No Flinch",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT} and do not flinch or wipe your mouth for 5 seconds.",
    failure: "Any flinch/wince/wipe within 5 seconds.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["tough"],
    modeWeights: { basic: 3, field: 4, final: 5 },
  },
  {
    id: 15,
    title: "Say It With Chest",
    category: "CONFIDENCE",
    instruction: 'Before drinking, say: "I know how to drink." Then take 1 {UNIT}.',
    failure: "You laugh while saying it or refuse to say it.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["meme"],
    modeWeights: { basic: 4, field: 4, final: 4 },
  },
  {
    id: 16,
    title: "Never Drink Alone",
    category: "SOCIAL",
    instruction: "Choose 1 player to drink with you. Both take 1 {UNIT}.",
    failure: "You take more than 5 seconds to choose.",
    penalty: "Both take 1 extra {UNIT}.",
    tags: ["pair"],
    modeWeights: { basic: 2, field: 5, final: 6 },
  },
  {
    id: 17,
    title: "Group Sync",
    category: "SOCIAL",
    instruction: "Everyone takes 1 {UNIT} at the same time (countdown 3-2-1).",
    failure: "Anyone drinks early or late.",
    penalty: "Early/late drinker takes 1 additional {UNIT}.",
    tags: ["group"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 18,
    title: "Toast Tax",
    category: "SOCIAL",
    instruction: "Current player proposes a 3-word toast. Then everyone takes 1 {UNIT}.",
    failure: "Toast is not exactly 3 words.",
    penalty: "Current player takes 1 extra {UNIT}.",
    tags: ["toast"],
    modeWeights: { basic: 3, field: 3, final: 3 },
  },
  {
    id: 19,
    title: "Match the Leader",
    category: "SOCIAL",
    instruction: "Find the fullest drink at the table. Everyone matches with 1 {UNIT}.",
    failure: "Anyone refuses to match.",
    penalty: "Refuser takes 2 {UNIT_PLURAL}.",
    tags: ["match"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 20,
    title: "Aux Privilege",
    category: "SOCIAL",
    instruction: "Whoever last touched the music/TV remote takes 1 {UNIT}.",
    failure: "Group can't agree within 10 seconds.",
    penalty: "Everyone takes 1 {UNIT}.",
    tags: ["aux"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 21,
    title: "Too Sober",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: 'You say "I\'m fine" or "I don\'t need it."',
    penalty: "Take 1 additional {UNIT}.",
    tags: ["correction"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 22,
    title: "Too Confident",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: "You celebrate afterward (cheer, fist pump, etc.).",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["correction"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 23,
    title: "Overthinking",
    category: "CORRECTION",
    instruction: "Stop talking for 5 seconds. Then take 1 {UNIT}.",
    failure: "You speak during the 5 seconds.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["shut up"],
    modeWeights: { basic: 1, field: 3, final: 6 },
  },
  {
    id: 24,
    title: "Hesitation Tax",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: "You ask for a clarification.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["strict"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 25,
    title: "Refill Shame",
    category: "CORRECTION",
    instruction: "If your drink is empty, refill it now. Then take 1 {UNIT}.",
    failure: "You refuse to refill.",
    penalty: "Take 2 {UNIT_PLURAL} anyway.",
    tags: ["refill"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 26,
    title: "Left of You Drinks",
    category: "SOCIAL",
    instruction: "The player to your left takes 1 {UNIT}.",
    failure: "You point the wrong person.",
    penalty: "You take 1 {UNIT} too.",
    tags: ["direction"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 27,
    title: "Right of You Drinks",
    category: "SOCIAL",
    instruction: "The player to your right takes 1 {UNIT}.",
    failure: "You point the wrong person.",
    penalty: "You take 1 {UNIT} too.",
    tags: ["direction"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 28,
    title: "Oldest Message",
    category: "SOCIAL",
    instruction: "Whoever last sent a message in the group chat takes 1 {UNIT}.",
    failure: "No one will admit it within 10 seconds.",
    penalty: "Everyone takes 1 {UNIT}.",
    tags: ["chat"],
    modeWeights: { basic: 1, field: 3, final: 4 },
  },
  {
    id: 29,
    title: "Most Recent Laugh",
    category: "SOCIAL",
    instruction: "The last person who laughed takes 1 {UNIT}.",
    failure: "Dispute lasts more than 10 seconds.",
    penalty: "Disputers each take 1 {UNIT}.",
    tags: ["laugh"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 30,
    title: "Hydration Paradox",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: 'Anyone says the word "water."',
    penalty: "That person takes 1 {UNIT} too.",
    tags: ["water"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 31,
    title: "Handshake Technique",
    category: "TECHNIQUE",
    instruction: "Shake hands with the person next to you, then both take 1 {UNIT}.",
    failure: "Handshake is refused.",
    penalty: "Refuser takes 1 additional {UNIT}.",
    tags: ["social"],
    modeWeights: { basic: 2, field: 3, final: 3 },
  },
  {
    id: 32,
    title: "No Tilt",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} without tilting your head (only the glass moves).",
    failure: "Your head tilts.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["form"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 33,
    title: "Eyes on the Horizon",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} while looking straight ahead (not at the drink).",
    failure: "You look at the drink.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["focus"],
    modeWeights: { basic: 3, field: 3, final: 4 },
  },
  {
    id: 34,
    title: "No Wipe",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} and don't wipe your mouth for 10 seconds.",
    failure: "You wipe within 10 seconds.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["discipline"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 35,
    title: "Two-Count Hold",
    category: "TECHNIQUE",
    instruction: "Hold the sip in your mouth for a count of 2, then swallow.",
    failure: "You swallow early.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["weird"],
    modeWeights: { basic: 1, field: 3, final: 4 },
  },
  {
    id: 36,
    title: "No Face",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT} and keep a neutral expression for 5 seconds.",
    failure: "Any grimace, smile, or laugh.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["pokerface"],
    modeWeights: { basic: 3, field: 4, final: 4 },
  },
  {
    id: 37,
    title: "Call It",
    category: "CONFIDENCE",
    instruction: 'Say "Light work" then take 1 {UNIT}.',
    failure: "You refuse to say it.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["taunt"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 38,
    title: "No Flinch, Again",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT}. Immediately after, stare at someone for 3 seconds.",
    failure: "You look away first.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["stare"],
    modeWeights: { basic: 2, field: 4, final: 4 },
  },
  {
    id: 39,
    title: "Instant Compliance",
    category: "CONFIDENCE",
    instruction: "Start drinking within 1 second of the card appearing.",
    failure: "You miss the 1 second window.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["fast"],
    modeWeights: { basic: 2, field: 4, final: 6 },
  },
  {
    id: 40,
    title: "No Excuses",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT}.",
    failure: 'You say any excuse phrase (e.g. "after this", "in a sec").',
    penalty: "Take 1 additional {UNIT}.",
    tags: ["strict"],
    modeWeights: { basic: 2, field: 4, final: 6 },
  },
  {
    id: 41,
    title: "Vote: Who Drinks",
    category: "SOCIAL",
    instruction: "Group points at one person. That person takes 2 {UNIT_PLURAL}.",
    failure: "No majority within 10 seconds.",
    penalty: "Everyone takes 1 {UNIT}.",
    tags: ["vote"],
    modeWeights: { basic: 1, field: 4, final: 5 },
  },
  {
    id: 42,
    title: "Last To React",
    category: "SOCIAL",
    instruction: "Everyone raises a hand. Last person to raise it takes 1 {UNIT}.",
    failure: "Someone refuses to participate.",
    penalty: "Refuser takes 1 {UNIT}.",
    tags: ["reflex"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 43,
    title: "Rock Paper Drinks",
    category: "SOCIAL",
    instruction: "You and the player of your choice play Rock-Paper-Scissors once. Loser takes 2 {UNIT_PLURAL}.",
    failure: "You take longer than 5 seconds to choose opponent.",
    penalty: "You take 1 extra {UNIT}.",
    tags: ["rps"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 44,
    title: "Cheers Check",
    category: "SOCIAL",
    instruction: "Everyone must cheers (clink or gesture) then take 1 {UNIT}.",
    failure: "Anyone doesn't cheers.",
    penalty: "Non-cheers person takes 1 additional {UNIT}.",
    tags: ["cheers"],
    modeWeights: { basic: 3, field: 3, final: 3 },
  },
  {
    id: 45,
    title: "Silence Tax",
    category: "CORRECTION",
    instruction: "If you've been quiet for the last minute, take 1 {UNIT}. (Group decides.)",
    failure: "You argue the group's decision.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["quiet"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 46,
    title: "No Names",
    category: "SOCIAL",
    instruction: "For the next 60 seconds, you may not say any player's name. Start by taking 1 {UNIT}.",
    failure: "You say any player's name.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["timed"],
    modeWeights: { basic: 1, field: 4, final: 5 },
  },
  {
    id: 47,
    title: "No Swears",
    category: "SOCIAL",
    instruction: "For the next 60 seconds, no swearing. Current player takes 1 {UNIT} to start.",
    failure: "You swear.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["timed"],
    modeWeights: { basic: 1, field: 4, final: 4 },
  },
  {
    id: 48,
    title: "No Questions",
    category: "SOCIAL",
    instruction: "For the next 60 seconds, you can't ask questions. Start with 1 {UNIT}.",
    failure: "You ask a question (ends with a question mark or uses question tone).",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["timed"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 49,
    title: "Word Ban: 'Bro'",
    category: "SOCIAL",
    instruction: "For the next 60 seconds, the word 'bro' is banned. Current player takes 1 {UNIT}.",
    failure: "You say 'bro'.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["timed", "bro"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 50,
    title: "No Phone",
    category: "CORRECTION",
    instruction: "For the next 5 minutes, if you touch your phone you take 2 {UNIT_PLURAL}. Current player takes 1 {UNIT} now.",
    failure: "You touch your phone within 5 minutes.",
    penalty: "Take 2 {UNIT_PLURAL} immediately.",
    tags: ["phone"],
    modeWeights: { basic: 0, field: 3, final: 5 },
  },
  {
    id: 51,
    title: "Two Sips, One Breath",
    category: "TECHNIQUE",
    instruction: "Take 2 {UNIT_PLURAL} back-to-back without taking a breath between them.",
    failure: "You breathe between sips.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["breath"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 52,
    title: "Sip & Salute",
    category: "TECHNIQUE",
    instruction: "Salute the room, then take 1 {UNIT}.",
    failure: "No salute.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["salute"],
    modeWeights: { basic: 3, field: 3, final: 3 },
  },
  {
    id: 53,
    title: "Table Tap",
    category: "TECHNIQUE",
    instruction: "Tap the table twice, then take 1 {UNIT}.",
    failure: "Wrong number of taps.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["ritual"],
    modeWeights: { basic: 3, field: 3, final: 3 },
  },
  {
    id: 54,
    title: "No Teeth",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} without showing your teeth (lips closed, drink clean).",
    failure: "Teeth visible.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["weird"],
    modeWeights: { basic: 1, field: 3, final: 4 },
  },
  {
    id: 55,
    title: "Slow Is Fast",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT} as slowly as possible without stopping.",
    failure: "You stop mid-sip.",
    penalty: "Take 1 additional {UNIT} normally.",
    tags: ["control"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 56,
    title: "Confession Tax",
    category: "SOCIAL",
    instruction: "Say one embarrassing word (single word only), then take 1 {UNIT}.",
    failure: "You say more than one word.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["oneword"],
    modeWeights: { basic: 2, field: 3, final: 3 },
  },
  {
    id: 57,
    title: "Hype Man",
    category: "SOCIAL",
    instruction: "Pick one player. Hype them up for 5 seconds. Then both take 1 {UNIT}.",
    failure: "You insult them instead.",
    penalty: "You take 2 {UNIT_PLURAL}.",
    tags: ["hype"],
    modeWeights: { basic: 2, field: 3, final: 3 },
  },
  {
    id: 58,
    title: "Snitch Rule",
    category: "SOCIAL",
    instruction: "If anyone has broken a timed rule tonight, they take 1 {UNIT}. (Group decides.)",
    failure: "You deny it after being called out.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["callout"],
    modeWeights: { basic: 0, field: 3, final: 5 },
  },
  {
    id: 59,
    title: "Last To Drink",
    category: "SOCIAL",
    instruction: "Everyone must take 1 {UNIT}. Last person to start drinking takes 1 extra {UNIT}.",
    failure: "You purposely delay to game it.",
    penalty: "You take 2 extra {UNIT_PLURAL}.",
    tags: ["race"],
    modeWeights: { basic: 2, field: 4, final: 5 },
  },
  {
    id: 60,
    title: "Refill Race",
    category: "SOCIAL",
    instruction: "If you need a refill, you must refill right now. Anyone refilling takes 1 {UNIT} after refilling.",
    failure: "You say 'I'm good' then refill later.",
    penalty: "Take 2 {UNIT_PLURAL} when you finally refill.",
    tags: ["refill"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 61,
    title: "Double Down",
    category: "BASIC",
    instruction: "Take 1 {UNIT}.",
    failure: "You complain about the card.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["complain"],
    modeWeights: { basic: 3, field: 4, final: 5 },
  },
  {
    id: 62,
    title: "One More For Safety",
    category: "BASIC",
    instruction: 'Take 1 {UNIT} "to be safe."',
    failure: "You say 'that makes no sense.'",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["meme"],
    modeWeights: { basic: 4, field: 4, final: 4 },
  },
  {
    id: 63,
    title: "Catch Up",
    category: "CORRECTION",
    instruction: "If your drink is currently more than half full, take 2 {UNIT_PLURAL}. Otherwise take 1 {UNIT}.",
    failure: "You lie about your drink level.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["catchup"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 64,
    title: "Still Standing",
    category: "CORRECTION",
    instruction: "If you are standing, take 1 {UNIT}. If you are sitting, take 2 {UNIT_PLURAL}.",
    failure: "You change position to dodge it.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["position"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 65,
    title: "Talking Too Much",
    category: "CORRECTION",
    instruction: "If you have spoken in the last 10 seconds, take 1 {UNIT}.",
    failure: "You claim you haven't.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["talk"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 66,
    title: "Mirror",
    category: "TECHNIQUE",
    instruction: "Copy the person to your left: same posture, then take 1 {UNIT}.",
    failure: "You don't match within 5 seconds.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["copy"],
    modeWeights: { basic: 2, field: 3, final: 3 },
  },
  {
    id: 67,
    title: "Reverse Grip",
    category: "TECHNIQUE",
    instruction: "Hold the drink in the most uncomfortable safe way you can, then take 1 {UNIT}.",
    failure: "You spill.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["awkward"],
    modeWeights: { basic: 1, field: 3, final: 4 },
  },
  {
    id: 68,
    title: "No Lips",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} without puckering your lips (group judges).",
    failure: "Group calls it a pucker.",
    penalty: "Repeat (another 1 {UNIT}).",
    tags: ["judge"],
    modeWeights: { basic: 1, field: 2, final: 4 },
  },
  {
    id: 69,
    title: "Hold The Cup",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} while holding your drink at arm's length.",
    failure: "You bring it closer before sipping.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["arm"],
    modeWeights: { basic: 2, field: 2, final: 3 },
  },
  {
    id: 70,
    title: "Precision",
    category: "TECHNIQUE",
    instruction: "Take exactly one normal sip (not tiny, not huge).",
    failure: "Group calls it tiny or huge.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["judge"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 71,
    title: "Declare Victory",
    category: "CONFIDENCE",
    instruction: 'Before drinking, say "I\'m built for this." Then take 1 {UNIT}.',
    failure: "You laugh while saying it.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["boast"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 72,
    title: "No Blink",
    category: "CONFIDENCE",
    instruction: "Stare at the screen and take 1 {UNIT} without blinking.",
    failure: "You blink.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["stare"],
    modeWeights: { basic: 1, field: 3, final: 4 },
  },
  {
    id: 73,
    title: "No Hands (Lite)",
    category: "TECHNIQUE",
    instruction: "Take 1 {UNIT} while the bottom of the glass stays on the table (lean in).",
    failure: "You lift the glass off the table.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["table"],
    modeWeights: { basic: 2, field: 3, final: 3 },
  },
  {
    id: 74,
    title: "Respect The Manual",
    category: "CONFIDENCE",
    instruction: 'Say "Yes, Manual." Then take 1 {UNIT}.',
    failure: "You refuse.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["yesboss"],
    modeWeights: { basic: 3, field: 3, final: 4 },
  },
  {
    id: 75,
    title: "Stone Cold",
    category: "CONFIDENCE",
    instruction: "Take 1 {UNIT}. Do not speak for the next full 15 seconds.",
    failure: "You speak or laugh audibly.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["silence"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 76,
    title: "Group Punishment",
    category: "SOCIAL",
    instruction: "Everyone takes 1 {UNIT}.",
    failure: "Anyone refuses.",
    penalty: "Refuser takes 2 {UNIT_PLURAL}.",
    tags: ["group"],
    modeWeights: { basic: 1, field: 4, final: 5 },
  },
  {
    id: 77,
    title: "Pick a Buddy",
    category: "SOCIAL",
    instruction: "Pick a buddy for the next 2 turns. Whenever either of you drinks, the other takes 1 {UNIT} too. Start now: both take 1 {UNIT}.",
    failure: "You can't agree on buddies within 10 seconds.",
    penalty: "You drink alone: take 2 {UNIT_PLURAL}.",
    tags: ["buddy"],
    modeWeights: { basic: 0, field: 3, final: 5 },
  },
  {
    id: 78,
    title: "Most Likely",
    category: "SOCIAL",
    instruction: "Group votes: who will be the messiest tonight? Winner takes 2 {UNIT_PLURAL}.",
    failure: "No majority in 10 seconds.",
    penalty: "Everyone takes 1 {UNIT}.",
    tags: ["vote"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 79,
    title: "Last To Arrive",
    category: "SOCIAL",
    instruction: "Whoever arrived last takes 1 {UNIT}.",
    failure: "If disputed longer than 10 seconds.",
    penalty: "Disputers each take 1 {UNIT}.",
    tags: ["arrival"],
    modeWeights: { basic: 2, field: 2, final: 3 },
  },
  {
    id: 80,
    title: "Host Tax",
    category: "SOCIAL",
    instruction: "If there is a host, host takes 1 {UNIT}. If no host, everyone takes 1 {UNIT}.",
    failure: "Host refuses.",
    penalty: "Host takes 1 extra {UNIT}.",
    tags: ["host"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 81,
    title: "Penalty Ladder",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: "You roll your eyes.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["attitude"],
    modeWeights: { basic: 0, field: 3, final: 6 },
  },
  {
    id: 82,
    title: "No Bargaining",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: 'You negotiate (e.g., "can I do half?").',
    penalty: "Take 1 additional {UNIT}.",
    tags: ["negotiate"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 83,
    title: "Too Slow",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: "You take longer than 5 seconds to start.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["slow"],
    modeWeights: { basic: 1, field: 4, final: 6 },
  },
  {
    id: 84,
    title: "Too Fast",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: "You finish it in under 1 second (tryhard).",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["tryhard"],
    modeWeights: { basic: 1, field: 3, final: 5 },
  },
  {
    id: 85,
    title: "The Manual Sees All",
    category: "CORRECTION",
    instruction: "Take 1 {UNIT}.",
    failure: "You say 'this game is rigged.'",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["rigged"],
    modeWeights: { basic: 0, field: 3, final: 6 },
  },
  {
    id: 86,
    title: "Water Break (Optional)",
    category: "BASIC",
    instruction: "Everyone takes a water sip or a normal sip (player choice).",
    failure: "Anyone complains about water.",
    penalty: "Complainer takes 1 additional {UNIT}.",
    tags: ["waterbreak"],
    modeWeights: { basic: 0, field: 1, final: 1 },
  },
  {
    id: 87,
    title: "Reset The Vibe",
    category: "SOCIAL",
    instruction: "Everyone cheers. Then everyone takes 1 {UNIT}.",
    failure: "Anyone doesn't cheer.",
    penalty: "Non-cheerer takes 1 extra {UNIT}.",
    tags: ["cheer"],
    modeWeights: { basic: 2, field: 3, final: 3 },
  },
  {
    id: 88,
    title: "Silent Agreement",
    category: "SOCIAL",
    instruction: "Everyone nods in silence for 3 seconds, then takes 1 {UNIT}.",
    failure: "Anyone speaks during the 3 seconds.",
    penalty: "Speaker takes 1 additional {UNIT}.",
    tags: ["silence"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 89,
    title: "Stand & Deliver",
    category: "CONFIDENCE",
    instruction: "Stand up, take 1 {UNIT}, sit down.",
    failure: "You don't stand fully upright.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["stand"],
    modeWeights: { basic: 2, field: 3, final: 4 },
  },
  {
    id: 90,
    title: "The Look",
    category: "CONFIDENCE",
    instruction: "Choose someone. Maintain eye contact while both take 1 {UNIT}.",
    failure: "You break eye contact first.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["eyecontact"],
    modeWeights: { basic: 1, field: 3, final: 4 },
  },
  {
    id: 91,
    title: "Practical Exam I",
    category: "EXAM",
    instruction: "Take 2 {UNIT_PLURAL}.",
    failure: "You delay more than 2 seconds.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["exam"],
    modeWeights: { basic: 0, field: 1, final: 4 },
  },
  {
    id: 92,
    title: "Practical Exam II",
    category: "EXAM",
    instruction: "Take 3 {UNIT_PLURAL}.",
    failure: "You pause more than 2 seconds between any sips.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["exam"],
    modeWeights: { basic: 0, field: 1, final: 4 },
  },
  {
    id: 93,
    title: "Group Exam",
    category: "EXAM",
    instruction: "Everyone takes 1 {UNIT}. Current player takes 1 extra {UNIT}.",
    failure: "Anyone refuses.",
    penalty: "Refuser takes 2 {UNIT_PLURAL}.",
    tags: ["exam", "group"],
    modeWeights: { basic: 0, field: 1, final: 4 },
  },
  {
    id: 94,
    title: "Oral Exam",
    category: "EXAM",
    instruction: 'Say "I have mastered drinking." Then take 2 {UNIT_PLURAL}.',
    failure: "You laugh or refuse.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["exam"],
    modeWeights: { basic: 0, field: 1, final: 3 },
  },
  {
    id: 95,
    title: "Speed Exam",
    category: "EXAM",
    instruction: "Finish 2 {UNIT_PLURAL} within 5 seconds.",
    failure: "Over 5 seconds.",
    penalty: "Take 1 additional {UNIT}.",
    tags: ["exam", "speed"],
    modeWeights: { basic: 0, field: 0, final: 4 },
  },
  {
    id: 96,
    title: "Composure Exam",
    category: "EXAM",
    instruction: "Take 2 {UNIT_PLURAL} with a straight face for 10 seconds after.",
    failure: "Any smile/laugh/sound in 10 seconds.",
    penalty: "Take 1 extra {UNIT}.",
    tags: ["exam"],
    modeWeights: { basic: 0, field: 1, final: 4 },
  },
  {
    id: 97,
    title: "Buddy Exam",
    category: "EXAM",
    instruction: "Pick a buddy in 3 seconds. Both take 2 {UNIT_PLURAL}.",
    failure: "You miss the 3 second window.",
    penalty: "You take 3 {UNIT_PLURAL} alone.",
    tags: ["exam", "buddy"],
    modeWeights: { basic: 0, field: 1, final: 4 },
  },
  {
    id: 98,
    title: "Discipline Exam",
    category: "EXAM",
    instruction: "Take 1 {UNIT}. Do not speak for 30 seconds.",
    failure: "You speak.",
    penalty: "Take 2 {UNIT_PLURAL}.",
    tags: ["exam", "silence"],
    modeWeights: { basic: 0, field: 1, final: 3 },
  },
  {
    id: 99,
    title: "Final Boss",
    category: "EXAM",
    instruction: "Everyone takes 2 {UNIT_PLURAL}.",
    failure: "Anyone refuses.",
    penalty: "Refuser takes 3 {UNIT_PLURAL}.",
    tags: ["exam", "group"],
    modeWeights: { basic: 0, field: 0, final: 3 },
  },
  {
    id: 100,
    title: "Graduation",
    category: "EXAM",
    instruction: "Current player takes 3 {UNIT_PLURAL}. Then assigns 1 {UNIT} to any one player.",
    failure: "You try to assign to yourself.",
    penalty: "You take 1 extra {UNIT} instead.",
    tags: ["exam", "assign"],
    modeWeights: { basic: 0, field: 1, final: 3 },
  },
];
